"""
MediKiosk — ClinicalFact Pydantic Schema
The immutable, audited core data model. Every intake channel writes into this structure.
Ref: MediKiosk_Full_Context_Handoff.md Section 4
"""

from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime


class SourceReference(BaseModel):
    """Provenance link — traces every fact to its origin (audio waveform or pixel polygon)."""
    type: Literal["patient_voice", "document_ocr", "touch_input", "explain_back_verified"]
    document_id: Optional[str] = None
    line_indices: Optional[list[int]] = None
    bbox: Optional[list[int]] = None       # [x1, y1, x2, y2] pixel coordinates
    ocr_confidence: Optional[float] = None
    raw_text: Optional[str] = None
    audio_timestamp_ms: Optional[int] = None


class ConfidenceBreakdown(BaseModel):
    """
    Deterministic confidence arithmetic:
    Confidence = tier_score × input_quality × completeness

    Tiers:
      ≥ 0.85 → High (locked, no further verification needed)
      0.55–0.85 → Medium (requires explain-back patient confirmation)
      < 0.55 → Refuse (flag for human physician review)
    """
    tier_score: float = Field(ge=0.0, le=1.0, description="Touch=1.0, Embedding=cosine(0.82-0.98), LLM=capped 0.70")
    input_quality: float = Field(ge=0.0, le=1.0, description="OCR or ASR engine confidence metric")
    completeness: float = Field(ge=0.0, le=1.0, description="filled_fields / required_fields")


class ClinicalFact(BaseModel):
    """
    The core data model — every piece of clinical information captured by MediKiosk.
    Immutable once confirmed. Audited with full provenance chain.
    """
    id: str = Field(description="UUID for this fact")
    encounter_id: str = Field(description="Parent encounter UUID")

    category: Literal[
        "chief_complaint", "symptom", "medication", "allergy",
        "vital", "lab_result", "family_history", "surgical_history",
        "ayush_agni", "ayush_prakriti", "ayush_ahara", "ayush_koshtha"
    ]
    field: str = Field(description="Specific field name within the category")
    value: str = Field(description="The clinical value captured")

    dose: Optional[str] = None
    frequency: Optional[str] = None
    patient_words: Optional[str] = Field(default=None, description="Original verbatim patient statement")
    normalized_concept: Optional[str] = Field(default=None, description="Standardized medical concept name")
    concept_code: Optional[str] = Field(default=None, description="SNOMED:xxxxx or NAMASTE:xxxxx code")

    provenance_tier: Literal["TOUCH", "LOOKUP", "EMBEDDING", "LLM", "OCR", "VOICE"] = Field(
        description="How was this fact derived? Touch=direct input, Embedding=vector match, LLM=model extraction"
    )
    source_type: Optional[Literal[
        "patient_voice", "document_ocr", "explain_back_verified", "touch_input"
    ]] = None
    source_reference: Optional[SourceReference] = None

    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    confidence_breakdown: Optional[ConfidenceBreakdown] = None

    temporal_state: Optional[Literal["prescribed", "taking", "stopped", "dose_changed"]] = None
    valid_from: Optional[str] = None
    valid_until: Optional[str] = None

    is_negated: bool = Field(default=False, description="True if patient explicitly denied this symptom/condition")
    status: Literal[
        "pending", "patient_confirmed", "explain_back_verified", "doctor_reviewed"
    ] = "pending"

    created_at: Optional[datetime] = None

    def confidence_tier(self) -> str:
        """Return the human-readable confidence tier for UI display."""
        if self.confidence >= 0.85:
            return "HIGH"
        elif self.confidence >= 0.55:
            return "MEDIUM"
        else:
            return "LOW_REFUSE"


class ClinicalFactCreate(BaseModel):
    """Schema for creating a new clinical fact (without auto-generated fields)."""
    encounter_id: str
    category: str
    field: str
    value: str
    dose: Optional[str] = None
    frequency: Optional[str] = None
    patient_words: Optional[str] = None
    normalized_concept: Optional[str] = None
    concept_code: Optional[str] = None
    provenance_tier: str = "TOUCH"
    source_type: Optional[str] = None
    source_reference: Optional[SourceReference] = None
    confidence: float = 1.0
    confidence_breakdown: Optional[ConfidenceBreakdown] = None
    temporal_state: Optional[str] = None
    valid_from: Optional[str] = None
    valid_until: Optional[str] = None
    is_negated: bool = False


class DrugInteractionAlert(BaseModel):
    """Alert generated by the deterministic drug-drug interaction engine."""
    drug_a: str
    drug_b: str
    severity: Literal["CRITICAL", "HIGH", "MODERATE", "LOW"]
    clinical_warning: str
    evidence_source: str


class LabResultAlert(BaseModel):
    """Alert generated by the abnormal lab value checker."""
    test_name: str
    display_name: Optional[str] = None
    measured_value: float
    unit: str
    status: Literal["NORMAL", "LOW", "HIGH", "CRITICAL_LOW", "CRITICAL_HIGH", "UNCONFIGURED_TEST"]
    reference_interval: str
    requires_urgent_escalation: bool = False
    interpretation: Optional[str] = None


class ClinicalGapAlert(BaseModel):
    """Alert generated by the proactive clinical gap detector."""
    gap_type: str
    condition_trigger: str
    missing_question: str
    clinical_rationale: str
    priority: Literal["HIGH", "MEDIUM"]
