import 'package:flutter/material.dart';

/// Language state provider with native Indian language localization strings
/// Supports: English (en), Hindi (hi), Tamil (ta), Telugu (te), Marathi (mr)
/// Ref: MEDIKIOSK_ANDROID_DESIGN_SPEC.md Section 3
class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'hi';

  String get currentLanguage => _currentLanguage;

  void setLanguage(String langCode) {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      notifyListeners();
    }
  }

  // Common UI Localization Dictionary
  String translate(String key) {
    final translations = _localizedStrings[_currentLanguage] ?? _localizedStrings['en']!;
    return translations[key] ?? _localizedStrings['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      // Welcome
      'welcome_title': 'Welcome to MediKiosk',
      'welcome_subtitle': 'Fast, Voice-Powered OPD Pre-Consultation Intake',
      'start_button': 'START INTAKE',
      'emergency_assistance_btn': 'Emergency? Tap for immediate assistance',
      'voice_call_fast_track_title': '1-Tap AI Voice Call',
      'voice_call_fast_track_sub': 'Skip forms and speak symptoms directly to AI',
      'helpline_card_title': '2G Toll-Free Phone Intake',
      'helpline_card_sub': 'For family with keypad phones: Dial 1800-890-AYUSH (Toll-Free, zero internet)',
      'clear': 'Clear',

      // Language Selection
      'select_language': 'Select Your Language',
      'choose_language_sub': 'Choose the language you are most comfortable speaking and reading',

      // Consent
      'consent_title': 'Patient Consent & Privacy Notice',
      'consent_body':
          'MediKiosk collects your symptoms and documents to assist your OPD doctor. Your information is protected under the Digital Personal Data Protection Act and will never be shared without consent.',
      'audio_explanation_title': 'Audio Explanation',
      'audio_explanation_sub': 'Tap to hear privacy terms aloud',
      'playing_notice': 'Playing notice in English...',
      'dpdp_bullet': 'Protected under Digital Personal Data Protection (DPDP) Act.',
      'doctor_use_bullet': 'Used only by your attending OPD doctor during this visit.',
      'auto_purge_bullet': 'Audio recordings and raw documents are automatically purged.',
      'agree_continue': 'I AGREE & CONTINUE',
      'decline_exit': 'Decline & Exit',

      // Identity
      'identify_title': 'Patient Identification',
      'identify_sub': 'Link your ABHA ID or enter phone number to fetch previous hospital records.',
      'scan_abha': 'Scan ABHA QR Code',
      'hold_card_camera': 'Hold health card or phone under camera',
      'open_qr_scanner': 'Open QR Scanner',
      'enter_mobile': 'Or Enter 10-Digit Mobile Number',
      'verify_phone': 'Verify Phone',
      'skip_identify': 'SKIP & PROCEED AS GUEST',

      // Care Stream
      'care_stream_title': 'Select Reason for Visit',
      'care_stream_sub': 'Select the clinic or medical department you wish to consult today.',
      'general_medicine_title': 'General Medicine',
      'general_medicine_sub': 'Fever, cough, cold, weakness, diabetes, blood pressure',
      'ayush_dept_title': 'AYUSH / Ayurveda',
      'ayush_dept_sub': 'Prakriti, chronic joint pain, digestive health, lifestyle',
      'pediatrics_dept_title': 'Pediatrics & Child Health',
      'pediatrics_dept_sub': 'Child immunization, growth, pediatric infections',
      'emergency_dept_title': 'Urgent / Emergency Care',
      'emergency_dept_sub': 'Chest pain, acute breathlessness, bleeding, trauma',
      'continue_intake': 'Continue to Intake',
      'continue_ayush_intake': 'Continue with AYUSH Intake',
      'continue_emergency_triage': 'Immediate Emergency Triaging',

      // Voice Intake & Active Capture
      'voice_intake_title': 'Tell Us What Is Bothering You',
      'tap_to_speak': 'TAP TO SPEAK',
      'listening': 'Listening... please speak',
      'speak_clearly_mic': 'Speak clearly near the microphone',
      'tap_wave_resume': 'Tap the wave or mic to resume listening',
      'speech_symptom_input': 'Speech / Symptom Input:',
      'tap_symptom_chip_prompt': 'Or tap a symptom below:',
      'type_or_select_hint': 'Type or select symptoms below...',
      'done_speaking': 'Done Speaking',
      'type_symptoms_link': 'Prefer typing? Tap here to type symptoms',
      'call_intake_shortcut_title': 'Speak with AI Doctor on simulated phone call',
      'call_intake_shortcut_btn': 'Start AI Doctor Call',
      'describe_symptoms_title': 'Describe Your Symptoms',
      'describe_symptoms_sub': 'Type your health complaints below or tap the quick symptom chips.',
      'submit_and_analyze': 'Submit Symptoms & Analyze',
      'switch_to_voice': 'Switch to Voice Intake',
      'describe_symptoms_hint': 'Describe your symptoms here...',

      // Chips
      'chip_fever': 'Fever',
      'chip_headache': 'Severe Headache',
      'chip_cough': 'Cough & Cold',
      'chip_stomach_pain': 'Stomach Pain',
      'chip_joint_pain': 'Joint Pain',
      'chip_chest_pain': 'Chest Pain',
      'chip_vomiting': 'Vomiting / Nausea',
      'chip_back_pain': 'Back Pain',
      'chip_breathlessness': 'Breathlessness',
      'chip_dizziness': 'Dizziness',

      // Followup
      'followup_title': 'Follow-Up Question',
      'followup_sub': 'Please answer this quick question to help your doctor understand better.',
      'confirm_answer': 'Confirm Answer',
      'skip_to_summary': 'Skip directly to Summary',

      // Processing
      'processing': 'Understanding Symptoms...',
      'processing_sub': 'Structuring facts and checking clinical safety guidelines...',

      // Summary
      'summary_title': 'Please Confirm What We Understood',
      'summary_sub': 'Check each item. Tap "Correct" to confirm or "Wrong" if incorrect.',
      'no_symptoms_title': 'No Symptoms Recorded Yet',
      'no_symptoms_sub': 'Tap "+ Add Another Symptom" below to speak or type your complaints.',
      'confirm_yes': 'Correct',
      'confirm_no': 'Wrong',
      'confirm_next': 'Confirm & Next',
      'add_another_symptom': '+ Add Another Symptom',
      'verified_badge': 'Verified',
      'patient_said': 'Patient said:',

      // Documents
      'doc_scan_title': 'Scan Your Old Prescription or Reports',
      'doc_scan_sub': 'Scanning your previous prescriptions allows our AI to extract medication history.',
      'doc_prescription_check': 'Doctor prescriptions',
      'doc_lab_check': 'Blood & urine lab reports',
      'doc_discharge_check': 'Hospital discharge summaries',
      'scan_doc_btn': 'Scan Document',
      'no_doc_btn': "I Don't Have Documents / Skip",
      'extracted_meds_title': 'Medications Found in Prescription',
      'extracted_meds_sub': 'Extracted from your scanned document. Please verify these match your medicines.',
      'confirm_continue_meds': 'Confirm & Continue',
      'inspect_source_doc': 'Inspect Source Document',

      // Vitals
      'vitals_title': 'Vital Signs Measurement',
      'vitals_sub': 'Recorded from kiosk IoT sensors or verified by OPD nursing station.',
      'confirm_vitals_next': 'Confirm Vitals & Next',
      'bp_label': 'Blood Pressure',
      'hr_label': 'Heart Rate (Pulse)',
      'spo2_label': 'SpO2 (Oxygen)',
      'temp_label': 'Body Temperature',
      'sugar_label': 'Blood Sugar (Random)',
      'normal_status': 'NORMAL',

      // AYUSH
      'ayush_title': 'Ayurvedic Profile (Dashavidha Pariksha)',
      'ayush_sub': 'Dashavidha Pariksha pre-assessment for your Ayurvedic physician.',
      'agni_section_title': '1. Digestive Fire / Agni',
      'sama_agni': 'Sama Agni',
      'sama_agni_sub': 'Balanced appetite, normal digestion without discomfort',
      'vishama_agni': 'Vishama Agni',
      'vishama_agni_sub': 'Irregular digestion, gas, bloating, fluctuating appetite',
      'tikshna_agni': 'Tikshna Agni',
      'tikshna_agni_sub': 'Excessive appetite, heartburn, acidity, rapid digestion',
      'manda_agni': 'Manda Agni',
      'manda_agni_sub': 'Sluggish digestion, post-meal heaviness, low appetite',
      'ama_section_title': 'Metabolic Toxins / Ama Markers',
      'coated_tongue': 'White or yellowish coating on tongue',
      'morning_stiffness': 'Morning body heaviness or joint stiffness',
      'prakriti_section_title': '2. Body Constitution / Prakriti',
      'tridoshaja_title': 'Tridoshaja / Balanced',
      'tridoshaja_sub': 'Harmonious frame, balanced sleep, good resilience',
      'vata_title': 'Vata Dominant',
      'vata_sub': 'Light frame, dry skin, light sleep, cold intolerance',
      'pitta_title': 'Pitta Dominant',
      'pitta_sub': 'Medium frame, warm body, sharp hunger, heat sensitive',
      'kapha_title': 'Kapha Dominant',
      'kapha_sub': 'Broad sturdy build, calm demeanor, deep sleep, cold skin',
      'koshtha_section_title': '3. Bowel Constitution / Koshtha',
      'madhyama_koshtha': 'Madhyama (Regular bowels)',
      'krura_koshtha': 'Krura (Hard stools, constipation prone)',
      'mridu_koshtha': 'Mridu (Soft stools, sensitive bowels)',
      'continue_queue': 'Submit AYUSH Intake & Get Queue Token',

      // Queue
      'queue_title': 'Your OPD Token Number',
      'your_queue_token': 'YOUR QUEUE TOKEN',
      'patients_ahead': 'Patients Ahead of You',
      'est_wait': 'Estimated Wait Time',
      'hospital_services': 'Hospital Services',
      'hospital_map': 'Hospital Map',
      'finish_print_ticket': 'Finish Intake & Print Ticket',

      // Completion
      'completion_title': 'Intake Successfully Completed!',
      'completion_sub': 'Your summary and prescription data have been forwarded to Doctor Room 102.',
      'opd_ticket_issued': 'OPD TICKET ISSUED',
      'auto_reset_title': 'Session Privacy Auto-Reset',
      'auto_reset_sub': 'To protect your health data, all information will be cleared from this screen in',
      'reset_now': 'Finish & Reset Now',
      'keep_open': 'Keep Open',
      'reset_button': 'FINISH & RESET SCREEN',

      // Triage & Emergency
      'emergency_title': 'Emergency Medical Attention Needed',
      'emergency_alert_staff': 'ALERT OPD NURSE / ATTENDANT',
      'triage_alert_title': 'Emergency Triage Alert',
      'triage_alert_sub':
          'Our safety engine detected symptoms requiring prompt medical assessment. Do not wait in the normal queue.',
      'triage_steps_title': 'What to do right now:',
      'triage_step_1': 'Sit down calmly and do not exert yourself.',
      'triage_step_2': 'Show this screen to Room 1 (Emergency Triage).',
      'triage_step_3': 'Your token has been elevated to Priority Status (RED).',
      'go_emergency_room': 'Go Directly to Emergency Room',
      'continue_routine_intake': 'Continue Routine Intake',
      'immediate_emergency_help': 'Immediate Emergency Assistance',
      'immediate_emergency_sub': 'If you are having severe chest pain, loss of consciousness, or severe trauma, call emergency services immediately.',
      'casualty_line': 'Hospital Casualty Line: 011-2999-4444 (Dial 108)',
      'ambulance_dispatch_btn': 'Request Ambulance Dispatch',
      'return_to_intake': 'Return to Intake',
      'ambulance_dispatched_title': 'Ambulance Dispatched',
      'ambulance_dispatched_sub': 'Unit is en route to hospital emergency drop-off gate.',
      'estimated_arrival': 'ESTIMATED ARRIVAL',

      // Services & Map
      'hospital_services_title': 'Hospital Services & Counters',
      'hospital_services_sub': 'Live wait times and locations for essential hospital counters.',
      'hospital_map_title': 'OPD Wayfinding & Map',
      'hospital_map_sub': 'Indoor OPD Wayfinding guidance to consultation rooms.',
      'pharmacy_title': 'OPD Pharmacy',
      'pathology_title': 'Pathology & Blood Lab',
      'injection_title': 'Injection & Dressing Room',
      'radiology_title': 'Radiology & X-Ray',
      'ayush_dispensary_title': 'AYUSH Herbal Dispensary',

      // Call intake
      'active_call_title': 'Active Intake Call',
      'ai_doctor_speaking': 'AI Doctor is speaking...',
      'listening_for_symptoms': 'Listening for symptoms... please speak naturally...',
      'tap_symptoms_quiet_mic': 'Tap symptoms if microphone is quiet:',
    },

    'hi': {
      // Welcome
      'welcome_title': 'मेडीकिओस्क में आपका स्वागत है',
      'welcome_subtitle': 'तेज़, बोलकर लक्षण दर्ज करने की ओपीडी सुविधा',
      'start_button': 'शुरू करें',
      'emergency_assistance_btn': 'आपातकालीन सहायता चाहिए? यहाँ दबाएं',
      'voice_call_fast_track_title': '1-टैप एआई फोन कॉल',
      'voice_call_fast_track_sub': 'फॉर्म भरे बिना सीधे एआई डॉक्टर से बोलकर बताएं',
      'helpline_card_title': '2G टोल-फ्री फोन इनटेक',
      'helpline_card_sub': 'कीपैड फोन वाले परिवार के लिए: 1800-890-AYUSH पर डायल करें (मुफ्त, बिना इंटरनेट)',
      'clear': 'हटाएं',

      // Language Selection
      'select_language': 'अपनी भाषा चुनें',
      'choose_language_sub': 'अपनी पसंदीदा भाषा का चयन करें जिसमें आप सहज महसूस करते हैं',

      // Consent
      'consent_title': 'मरीज़ सहमति एवं गोपनीयता सूचना',
      'consent_body':
          'मेडीकिओस्क आपके डॉक्टर की सहायता के लिए आपकी परेशानी और पुरानी पर्चियों को सुरक्षित रूप से दर्ज करता है। आपका डेटा पूरी तरह सुरक्षित है।',
      'audio_explanation_title': 'ऑडियो द्वारा सुनें',
      'audio_explanation_sub': 'गोपनीयता नियम बोलकर सुनने के लिए दबाएं',
      'playing_notice': 'हिन्दी में नियम सुनाए जा रहे हैं...',
      'dpdp_bullet': 'डिजिटल व्यक्तिगत डेटा संरक्षण (DPDP) अधिनियम के तहत सुरक्षित।',
      'doctor_use_bullet': 'केवल इस ओपीडी परामर्श में उपस्थित डॉक्टर द्वारा उपयोग किया जाएगा।',
      'auto_purge_bullet': 'ऑडियो रिकॉर्डिंग और दस्तावेज़ स्वतः हटा दिए जाते हैं।',
      'agree_continue': 'मैं सहमत हूँ और आगे बढ़ें',
      'decline_exit': 'अस्वीकार करें व बाहर निकलें',

      // Identity
      'identify_title': 'मरीज़ पहचान',
      'identify_sub': 'पुराने अस्पताल रिकॉर्ड प्राप्त करने के लिए आभा आईडी या फोन नंबर दर्ज करें।',
      'scan_abha': 'आभा (ABHA) क्यूआर कोड स्कैन करें',
      'hold_card_camera': 'स्वास्थ्य कार्ड या फोन कैमरा के सामने रखें',
      'open_qr_scanner': 'क्यूआर स्कैनर खोलें',
      'enter_mobile': 'या 10-अंकों का मोबाइल नंबर दर्ज करें',
      'verify_phone': 'फोन सत्यापित करें',
      'skip_identify': 'पहचान छोड़ें (बिना पहचान आगे बढ़ें)',

      // Care Stream
      'care_stream_title': 'परामर्श विभाग का चयन करें',
      'care_stream_sub': 'आज आप किस विभाग में डॉक्टर से परामर्श लेना चाहते हैं?',
      'general_medicine_title': 'सामान्य चिकित्सा (जनरल मेडिसिन)',
      'general_medicine_sub': 'बुखार, खांसी, जुकाम, कमजोरी, बीपी, शुगर',
      'ayush_dept_title': 'आयुष एवं आयुर्वेद',
      'ayush_dept_sub': 'प्रकृति, जोड़ों का दर्द, पाचन समस्या, दिनचर्या',
      'pediatrics_dept_title': 'बाल रोग विभाग',
      'pediatrics_dept_sub': 'बच्चों का टीकाकरण, विकास, संक्रमण',
      'emergency_dept_title': 'आपातकालीन चिकित्सा',
      'emergency_dept_sub': 'सीने में तेज दर्द, सांस फूलना, चोट, रक्तस्राव',
      'continue_intake': 'लक्षण दर्ज करने आगे बढ़ें',
      'continue_ayush_intake': 'आयुष सेवन व परीक्षण शुरू करें',
      'continue_emergency_triage': 'तत्काल आपातकालीन सहायता',

      // Voice Intake & Active Capture
      'voice_intake_title': 'बोलकर अपनी परेशानी बताएं',
      'tap_to_speak': 'बोलने के लिए दबाएं',
      'listening': 'हम सुन रहे हैं... बोलिए',
      'speak_clearly_mic': 'कृपया माइक के पास साफ आवाज़ में बोलें',
      'tap_wave_resume': 'दोबारा सुनने के लिए माइक दबाएं',
      'speech_symptom_input': 'बोले गए लक्षण:',
      'tap_symptom_chip_prompt': 'या नीचे से अपने लक्षण चुनें:',
      'type_or_select_hint': 'यहाँ टाइप करें या नीचे से लक्षण चुनें...',
      'done_speaking': 'बोलना समाप्त हुआ',
      'type_symptoms_link': 'टाइप करना चाहते हैं? यहाँ दबाएं',
      'call_intake_shortcut_title': 'एआई डॉक्टर से फोन कॉल पर बात करें',
      'call_intake_shortcut_btn': 'एआई कॉल शुरू करें',
      'describe_symptoms_title': 'अपने लक्षण बताएं',
      'describe_symptoms_sub': 'नीचे अपनी समस्या लिखें या सामान्य लक्षणों पर टैप करें।',
      'submit_and_analyze': 'लक्षण दर्ज करें और विश्लेषण करें',
      'switch_to_voice': 'बोलकर बताने पर जाएं',
      'describe_symptoms_hint': 'यहाँ अपने लक्षण विस्तार से लिखें...',

      // Chips
      'chip_fever': 'बुखार',
      'chip_headache': 'तेज सिरदर्द',
      'chip_cough': 'खांसी और जुकाम',
      'chip_stomach_pain': 'पेट दर्द',
      'chip_joint_pain': 'जोड़ों का दर्द',
      'chip_chest_pain': 'सीने में दर्द',
      'chip_vomiting': 'उल्टी या जी मिचलाना',
      'chip_back_pain': 'कमर या पीठ दर्द',
      'chip_breathlessness': 'सांस लेने में तकलीफ',
      'chip_dizziness': 'चक्कर आना',

      // Followup
      'followup_title': 'आवश्यक अनुवर्ती प्रश्न',
      'followup_sub': 'डॉक्टर की बेहतर समझ के लिए कृपया इस प्रश्न का उत्तर दें।',
      'confirm_answer': 'उत्तर की पुष्टि करें',
      'skip_to_summary': 'सीधे सारांश पर जाएं',

      // Processing
      'processing': 'जानकारी समझ रहे हैं...',
      'processing_sub': 'लक्षणों को व्यवस्थित कर नैदानिक सुरक्षा जांची जा रही है...',

      // Summary
      'summary_title': 'कृपया जाँचे जो हमने समझा',
      'summary_sub': 'प्रत्येक लक्षण देखें। पुष्टि के लिए "सही है" या बदलने के लिए "गलत है" दबाएं।',
      'no_symptoms_title': 'अभी कोई लक्षण दर्ज नहीं हुआ',
      'no_symptoms_sub': 'बोलकर या लिखकर लक्षण दर्ज करने के लिए नीचे बटन दबाएं।',
      'confirm_yes': 'हाँ, सही है',
      'confirm_no': 'नहीं, गलत है',
      'confirm_next': 'पुष्टि करें और आगे बढ़ें',
      'add_another_symptom': '+ अन्य लक्षण जोड़ें',
      'verified_badge': 'सत्यापित',
      'patient_said': 'मरीज़ ने कहा:',

      // Documents
      'doc_scan_title': 'पुरानी पर्ची या जाँच रिपोर्ट स्कैन करें',
      'doc_scan_sub': 'पुरानी पर्ची स्कैन करने से एआई पिछली दवाइयों की जानकारी डॉक्टर को दिखाता है।',
      'doc_prescription_check': 'डॉक्टर की पुरानी पर्ची',
      'doc_lab_check': 'खून व पेशाब की जाँच रिपोर्ट',
      'doc_discharge_check': 'अस्पताल डिस्चार्ज समरी',
      'scan_doc_btn': 'दस्तावेज़ स्कैन करें',
      'no_doc_btn': 'मेरे पास पर्ची नहीं है / आगे बढ़ें',
      'extracted_meds_title': 'पर्चे से मिली दवाइयाँ',
      'extracted_meds_sub': 'दस्तावेज़ से निकाली गई दवाएँ। कृपया जांचें कि ये आपकी दवाएँ हैं।',
      'confirm_continue_meds': 'दवाएँ सही हैं और आगे बढ़ें',
      'inspect_source_doc': 'मूल पर्ची देखें',

      // Vitals
      'vitals_title': 'शारीरिक माप (Vitals)',
      'vitals_sub': 'कियोस्क सेंसर या नर्सिंग स्टेशन द्वारा दर्ज माप।',
      'confirm_vitals_next': 'माप की पुष्टि करें और आगे बढ़ें',
      'bp_label': 'रक्तचाप (Blood Pressure)',
      'hr_label': 'नाड़ी दर (Heart Rate)',
      'spo2_label': 'ऑक्सीजन (SpO2)',
      'temp_label': 'शरीर का तापमान',
      'sugar_label': 'ब्लड शुगर (रैंडम)',
      'normal_status': 'सामान्य',

      // AYUSH
      'ayush_title': 'आयुर्वेदिक प्रकृति व अग्नि परीक्षण',
      'ayush_sub': 'दशविध परीक्षा पूर्व-मूल्यांकन आपके आयुर्वेदिक चिकित्सक के लिए।',
      'agni_section_title': '१. पाचन शक्ति (अग्नि)',
      'sama_agni': 'सम अग्नि',
      'sama_agni_sub': 'संतुलित भूख, बिना किसी परेशानी के सामान्य पाचन',
      'vishama_agni': 'विषम अग्नि',
      'vishama_agni_sub': 'अनियमित पाचन, गैस, पेट फूलना, भूख में उतार-चढ़ाव',
      'tikshna_agni': 'तीक्ष्ण अग्नि',
      'tikshna_agni_sub': 'अत्यधिक भूख, सीने में जलन, एसिडिटी, बहुत तेज़ पाचन',
      'manda_agni': 'मन्द अग्नि',
      'manda_agni_sub': 'धीमा पाचन, भोजन के बाद भारीपन, कम भूख',
      'ama_section_title': 'आम लक्षण (विषाक्त तत्व)',
      'coated_tongue': 'जीभ पर सफेद या पीली परत (जिह्वा लेप)',
      'morning_stiffness': 'सुबह शरीर में भारीपन या जोड़ों में जकड़न',
      'prakriti_section_title': '२. शारीरिक प्रकृति',
      'tridoshaja_title': 'त्रिदोषज (संतुलित प्रकृति)',
      'tridoshaja_sub': 'संतुलित शरीर, अच्छी नींद और रोग प्रतिरोधक क्षमता',
      'vata_title': 'वात प्रधान',
      'vata_sub': 'हल्का शरीर, रूखी त्वचा, हल्की नींद, ठंड बर्दाश्त न होना',
      'pitta_title': 'पित्त प्रधान',
      'pitta_sub': 'मध्यम शरीर, गर्म त्वचा, तेज भूख, गर्मी बर्दाश्त न होना',
      'kapha_title': 'कफ प्रधान',
      'kapha_sub': 'मजबूत शरीर, शांत स्वभाव, गहरी नींद, ठंडी त्वचा',
      'koshtha_section_title': '३. कोष्ठ (पेट साफ होना)',
      'madhyama_koshtha': 'मध्यम कोष्ठ (नियमित पेट साफ होना)',
      'krura_koshtha': 'क्रूर कोष्ठ (कब्ज की समस्या, सख्त मल)',
      'mridu_koshtha': 'मृदु कोष्ठ (आसानी से दस्त होना, संवेदनशील पेट)',
      'continue_queue': 'आयुष विवरण दर्ज करें व टोकन लें',

      // Queue
      'queue_title': 'आपका ओपीडी टोकन नंबर',
      'your_queue_token': 'आपका टोकन नंबर',
      'patients_ahead': 'आपसे पहले मरीज़',
      'est_wait': 'अनुमानित प्रतीक्षा समय',
      'hospital_services': 'अस्पताल सेवाएँ',
      'hospital_map': 'अस्पताल का नक्शा',
      'finish_print_ticket': 'पंजीकरण समाप्त करें व पर्ची लें',

      // Completion
      'completion_title': 'पंजीकरण सफलतापूर्वक पूरा हुआ!',
      'completion_sub': 'आपकी जानकारी और पर्चे का विवरण कमरा नंबर 102 में भेज दिया गया है।',
      'opd_ticket_issued': 'ओपीडी टोकन जारी',
      'auto_reset_title': 'गोपनीयता ऑटो-रीसेट',
      'auto_reset_sub': 'आपकी जानकारी सुरक्षित रखने के लिए यह स्क्रीन स्वतः रीसेट होगी:',
      'reset_now': 'अभी समाप्त करें',
      'keep_open': 'खुला रखें',
      'reset_button': 'समाप्त करें (RESET)',

      // Triage & Emergency
      'emergency_title': 'आपातकालीन सहायता की आवश्यकता',
      'emergency_alert_staff': 'ओपीडी नर्स को तुरंत सूचित करें',
      'triage_alert_title': 'आपातकालीन चेतावनी (रेड अलर्ट)',
      'triage_alert_sub':
          'आपके लक्षणों में तत्काल डॉक्टर की आवश्यकता है। सामान्य कतार में प्रतीक्षा न करें।',
      'triage_steps_title': 'अभी तुरंत क्या करें:',
      'triage_step_1': 'शांति से बैठ जाएं और शारीरिक श्रम न करें।',
      'triage_step_2': 'यह स्क्रीन कमरा नंबर 1 (इमरजेंसी) में दिखाएं।',
      'triage_step_3': 'आपके टोकन को आपातकालीन प्राथमिकता (RED) दी गई है।',
      'go_emergency_room': 'सीधे आपातकालीन कक्ष में जाएं',
      'continue_routine_intake': 'सामान्य प्रक्रिया जारी रखें',
      'immediate_emergency_help': 'तत्काल आपातकालीन सहायता',
      'immediate_emergency_sub': 'यदि अत्यधिक सीने में दर्द, बेहोशी या गंभीर चोट है तो तुरंत आपातकालीन सहायता लें।',
      'casualty_line': 'अस्पताल इमरजेंसी फोन: 011-2999-4444 (या 108 डायल करें)',
      'ambulance_dispatch_btn': 'एम्बुलेंस बुलाएं',
      'return_to_intake': 'वापस जाएं',
      'ambulance_dispatched_title': 'एम्बुलेंस रवाना हो चुकी है',
      'ambulance_dispatched_sub': 'गाड़ी अस्पताल के इमरजेंसी गेट की ओर आ रही है।',
      'estimated_arrival': 'अनुमानित आगमन समय',

      // Services & Map
      'hospital_services_title': 'अस्पताल सेवाएँ एवं दवाखाना',
      'hospital_services_sub': 'आवश्यक काउंटरों और सेवाओं की जानकारी और प्रतीक्षा समय।',
      'hospital_map_title': 'अस्पताल का नक्शा व दिशाएँ',
      'hospital_map_sub': 'ओपीडी कमरों तक पहुँचने के लिए इनडोर दिशा-निर्देश।',
      'pharmacy_title': 'ओपीडी दवाखाना (फार्मेसी)',
      'pathology_title': 'पैथोलॉजी व खून जाँच लैब',
      'injection_title': 'इंजेक्शन व ड्रेसिंग रूम',
      'radiology_title': 'रेडियोलॉजी व एक्स-रे',
      'ayush_dispensary_title': 'आयुष औषधि वितरण केंद्र',

      // Call intake
      'active_call_title': 'सक्रिय एआई डॉक्टर कॉल',
      'ai_doctor_speaking': 'एआई डॉक्टर बोल रहे हैं...',
      'listening_for_symptoms': 'हम आपके लक्षण सुन रहे हैं... कृपया बोलिए...',
      'tap_symptoms_quiet_mic': 'माइक न चलने पर लक्षण चुनें:',
    },

    'ta': {
      // Welcome
      'welcome_title': 'மெடிகியோஸ்கிற்கு நல்வரவு',
      'welcome_subtitle': 'வேகமான, குரல் வழி மருத்துவப் பதிவு மற்றும் ஓபிடி உதவி',
      'start_button': 'தொடங்குங்கள்',
      'emergency_assistance_btn': 'அவசர சிகிச்சையா? உடனே தட்டவும்',
      'voice_call_fast_track_title': '1-தட்டல் குரல் அழைப்பு',
      'voice_call_fast_track_sub': 'படிவங்கள் இல்லாமல் நேரடியாக AI மருத்துவரிடம் பேசுங்கள்',
      'helpline_card_title': '2G இலவச கட்டண தொலைபேசி பதிவு',
      'helpline_card_sub': 'கீபேட் போன்களுக்கு: 1800-890-AYUSH அழைக்கவும் (இலவசம், இணையம் தேவையில்லை)',
      'clear': 'அழி',

      // Language Selection
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'choose_language_sub': 'நீங்கள் பேசவும் படிக்கவும் விரும்பும் மொழியைத் தேர்வுசெய்யவும்',

      // Consent
      'consent_title': 'நோயாளி ஒப்புதல் மற்றும் தனியுரிமை',
      'consent_body': 'உங்கள் மருத்துவருக்கு உதவ உங்கள் அறிகுறிகள் மற்றும் ஆவணங்கள் சேகரிக்கப்படுகின்றன. உங்கள் தரவு முற்றிலும் பாதுகாப்பானது.',
      'audio_explanation_title': 'ஆடியோ விளக்கம்',
      'audio_explanation_sub': 'விதிமுறைகளை குரல் மூலம் கேட்க தட்டவும்',
      'playing_notice': 'தமிழில் விதிகள் ஒலிக்கப்படுகின்றன...',
      'dpdp_bullet': 'டிஜிட்டல் தனிநபர் தரவு பாதுகாப்புச் சட்டத்தின் கீழ் பாதுகாக்கப்படுகிறது.',
      'doctor_use_bullet': 'இந்த ஆலோசனையில் உள்ள மருத்துவருக்கு மட்டுமே காட்டப்படும்.',
      'auto_purge_bullet': 'ஆடியோ பதிவுகள் மற்றும் ஆவணங்கள் தானாக அழிக்கப்படும்.',
      'agree_continue': 'நான் ஒப்புக்கொள்கிறேன்',
      'decline_exit': 'நிராகரித்து வெளியேறு',

      // Identity
      'identify_title': 'நோயாளி அடையாளம்',
      'identify_sub': 'முந்தைய மருத்துவ பதிவுகளைப் பெற ABHA QR அல்லது தொலைபேசி எண்ணை உள்ளிடவும்.',
      'scan_abha': 'ABHA QR குறியீட்டை ஸ்கேன் செய்யுங்கள்',
      'hold_card_camera': 'அட்டையை கேமராவுக்கு முன் காட்டவும்',
      'open_qr_scanner': 'QR ஸ்கேனரைத் திறக்கவும்',
      'enter_mobile': 'அல்லது 10-இலக்க மொபைல் எண்ணை உள்ளிடவும்',
      'verify_phone': 'எண்ணை உறுதிப்படுத்தவும்',
      'skip_identify': 'தவிர்த்து செல்லவும் (விருந்தினராக)',

      // Care Stream
      'care_stream_title': 'பிரிவைத் தேர்ந்தெடுக்கவும்',
      'care_stream_sub': 'இன்று நீங்கள் பார்க்க விரும்பும் மருத்துவப் பிரிவைத் தேர்வுசெய்யவும்.',
      'general_medicine_title': 'பொது மருத்துவம்',
      'general_medicine_sub': 'காய்ச்சல், இருமல், சளி, சோர்வு, நீரிழிவு, இரத்த அழுத்தம்',
      'ayush_dept_title': 'ஆயுஷ் மற்றும் ஆயுர்வேதம்',
      'ayush_dept_sub': 'மூட்டு வலி, செரிமான பிரச்சனை, பிரகிருதி, வாழ்க்கை முறை',
      'pediatrics_dept_title': 'குழந்தைகள் நலம்',
      'pediatrics_dept_sub': 'குழந்தை தடுப்பூசி, வளர்ச்சி, குழந்தைகள் நோய்த்தொற்று',
      'emergency_dept_title': 'அவசர சிகிச்சை பிரிவு',
      'emergency_dept_sub': 'நெஞ்சு வலி, கடுமையான மூச்சுத்திணறல், விபத்து, ரத்தப்போக்கு',
      'continue_intake': 'பதிவைத் தொடரவும்',
      'continue_ayush_intake': 'ஆயுஷ் பதிவைத் தொடங்கவும்',
      'continue_emergency_triage': 'உடனடி அவசர சிகிச்சை',

      // Voice Intake & Active Capture
      'voice_intake_title': 'உங்கள் பிரச்சனையை பேசுங்கள்',
      'tap_to_speak': 'பேச தட்டவும்',
      'listening': 'கேட்கிறது... பேசுங்கள்',
      'speak_clearly_mic': 'மைக் அருகே தெளிவாகப் பேசவும்',
      'tap_wave_resume': 'மீண்டும் பேச தட்டவும்',
      'speech_symptom_input': 'பேசிய அறிகுறிகள்:',
      'tap_symptom_chip_prompt': 'அல்லது கீழே உள்ள அறிகுறிகளைத் தேர்ந்தெடுக்கவும்:',
      'type_or_select_hint': 'இங்கே தட்டச்சு செய்யவும் அல்லது தேர்ந்தெடுக்கவும்...',
      'done_speaking': 'பேசி முடித்தேன்',
      'type_symptoms_link': 'தட்டச்சு செய்ய விரும்புகிறீர்களா? இங்கே தட்டவும்',
      'call_intake_shortcut_title': 'AI மருத்துவரிடம் தொலைபேசி அழைப்பில் பேசவும்',
      'call_intake_shortcut_btn': 'AI அழைப்பைத் தொடங்கவும்',
      'describe_symptoms_title': 'உங்கள் அறிகுறிகளை விவரிக்கவும்',
      'describe_symptoms_sub': 'கீழே உங்கள் புகார்களை தட்டச்சு செய்யவும் அல்லது அறிகுறிகளைத் தேர்ந்தெடுக்கவும்.',
      'submit_and_analyze': 'அறிகுறிகளைச் சமர்ப்பித்து ஆய்வு செய்',
      'switch_to_voice': 'குரல் மூலமான பதிவுக்கு மாறவும்',
      'describe_symptoms_hint': 'உங்கள் அறிகுறிகளை இங்கே தட்டச்சு செய்யவும்...',

      // Chips
      'chip_fever': 'காய்ச்சல்',
      'chip_headache': 'கடுமையான தலைவலி',
      'chip_cough': 'இருமல் மற்றும் சளி',
      'chip_stomach_pain': 'வயிற்று வலி',
      'chip_joint_pain': 'மூட்டு வலி',
      'chip_chest_pain': 'நெஞ்சு வலி',
      'chip_vomiting': 'வாந்தி அல்லது குமட்டல்',
      'chip_back_pain': 'முதுகு அல்லது இடுப்பு வலி',
      'chip_breathlessness': 'மூச்சுத் திணறல்',
      'chip_dizziness': 'தலைச்சுற்றல்',

      // Followup
      'followup_title': 'துணை கேள்வி',
      'followup_sub': 'மருத்துவருக்குத் துல்லியமாகப் புரிய இந்த கேள்விக்கு பதிலளிக்கவும்.',
      'confirm_answer': 'பதிலை உறுதிப்படுத்தவும்',
      'skip_to_summary': 'நேரடியாக சுருக்கத்திற்குச் செல்லவும்',

      // Processing
      'processing': 'செயலாக்குகிறது...',
      'processing_sub': 'மருத்துவ விவரங்கள் புரிந்துகொள்ளப்படுகின்றன...',

      // Summary
      'summary_title': 'விவரங்களை உறுதிப்படுத்தவும்',
      'summary_sub': 'ஒவ்வொரு விவரத்தையும் சரிபார்க்கவும். உறுதிப்படுத்த "சரி" அல்லது "தவறு" தட்டவும்.',
      'no_symptoms_title': 'அறிகுறிகள் எதுவும் இன்னும் பதிவாகவில்லை',
      'no_symptoms_sub': 'பேச அல்லது எழுத கீழே உள்ள பொத்தானைத் தட்டவும்.',
      'confirm_yes': 'ஆம், சரி',
      'confirm_no': 'இல்லை, தவறு',
      'confirm_next': 'உறுதிசெய்து தொடரவும்',
      'add_another_symptom': '+ மற்றொரு அறிகுறியைச் சேர்க்கவும்',
      'verified_badge': 'சரிபார்க்கப்பட்டது',
      'patient_said': 'நோயாளி கூறியது:',

      // Documents
      'doc_scan_title': 'பழைய மருந்துச்சீட்டை ஸ்கேன் செய்யவும்',
      'doc_scan_sub': 'பழைய சீட்டை ஸ்கேன் செய்வது உங்கள் முந்தைய மருந்துகளை அறிய உதவுகிறது.',
      'doc_prescription_check': 'மருத்துவர் சீட்டு',
      'doc_lab_check': 'இரத்த, சிறுநீர் பரிசோதனை அறிக்கைகள்',
      'doc_discharge_check': 'டிஸ்சார்ஜ் அறிக்கை',
      'scan_doc_btn': 'சீட்டை ஸ்கேன் செய்யவும்',
      'no_doc_btn': 'சீட்டு இல்லை / தொடரவும்',
      'extracted_meds_title': 'கண்டறியப்பட்ட மருந்துகள்',
      'extracted_meds_sub': 'உங்கள் ஆவணத்திலிருந்து எடுக்கப்பட்ட மருந்துகள். இவை சரியானதா என சரிபார்க்கவும்.',
      'confirm_continue_meds': 'மருந்துகள் சரி, தொடரவும்',
      'inspect_source_doc': 'அசல் சீட்டைக் காண்க',

      // Vitals
      'vitals_title': 'முக்கிய உடல் அறிகுறிகள் (Vitals)',
      'vitals_sub': 'சென்சார் அல்லது செவிலியர் மூலம் அளவிடப்பட்ட அளவுகள்.',
      'confirm_vitals_next': 'அளவுகளை உறுதிசெய்து தொடரவும்',
      'bp_label': 'இரத்த அழுத்தம் (BP)',
      'hr_label': 'நாடித் துடிப்பு (Heart Rate)',
      'spo2_label': 'ஆக்சிஜன் அளவு (SpO2)',
      'temp_label': 'உடல் வெப்பநிலை',
      'sugar_label': 'இரத்த சர்க்கரை அளவு',
      'normal_status': 'இயல்பானது',

      // AYUSH
      'ayush_title': 'ஆயுஷ் மருத்துவப் பதிவு',
      'ayush_sub': 'உங்கள் ஆயுர்வேத மருத்துவருக்கான தசவித பரீட்சை மதிப்பீடு.',
      'agni_section_title': '1. செரிமான சக்தி (அக்னி)',
      'sama_agni': 'சம அக்னி',
      'sama_agni_sub': 'சீரான பசி, இயல்பான செரிமானம்',
      'vishama_agni': 'விஷம அக்னி',
      'vishama_agni_sub': 'ஒழுங்கற்ற செரிமானம், வாயு, வயிற்று உப்புசம்',
      'tikshna_agni': 'தீக்ஷ்ண அக்னி',
      'tikshna_agni_sub': 'அதிக பசி, நெஞ்செரிச்சல், மிக விரைவான செரிமானம்',
      'manda_agni': 'மந்த அக்னி',
      'manda_agni_sub': 'மந்தமான செரிமானம், உணவு உண்ட பின் கனம், குறைந்த பசி',
      'ama_section_title': 'நச்சு அடையாளங்கள் (ஆமம்)',
      'coated_tongue': 'நாக்கில் வெள்ளை அல்லது மஞ்சள் படலம்',
      'morning_stiffness': 'காலையில் உடல் சோர்வு அல்லது மூட்டு இறுக்கம்',
      'prakriti_section_title': '2. உடல் பிரகிருதி',
      'tridoshaja_title': 'திரிதோஷ சமநிலை',
      'tridoshaja_sub': 'சீரான உடல், நல்ல தூக்கம் மற்றும் நோய் எதிர்ப்பு சக்தி',
      'vata_title': 'வாத ஆதிக்கம்',
      'vata_sub': 'மெலிந்த உடல், உலர் சருமம், லேசான தூக்கம், குளிர் தாங்காமை',
      'pitta_title': 'பித்த ஆதிக்கம்',
      'pitta_sub': 'நடுத்தர உடல், வெப்ப சருமம், அதிக பசி, வெப்பம் தாங்காமை',
      'kapha_title': 'கப ஆதிக்கம்',
      'kapha_sub': 'வலிமையான உடல், அமைதியான குணம், ஆழ்ந்த தூக்கம்',
      'koshtha_section_title': '3. மலக்குடல் தன்மை (கோஷ்டம்)',
      'madhyama_koshtha': 'மத்தியம கோஷ்டம் (வழக்கமான மலம் கழித்தல்)',
      'krura_koshtha': 'க்ரூர கோஷ்டம் (மலச்சிக்கல், கடின மலம்)',
      'mridu_koshtha': 'மிருது கோஷ்டம் (எளிதில் பேதி, மென்மையான குடல்)',
      'continue_queue': 'ஆயுஷ் தகவல்களைச் சமர்ப்பித்து டோக்கன் பெறவும்',

      // Queue
      'queue_title': 'உங்கள் டோக்கன் எண்',
      'your_queue_token': 'உங்கள் டோக்கன் எண்',
      'patients_ahead': 'முன்னுள்ள நோயாளிகள்',
      'est_wait': 'காத்திருப்பு நேரம்',
      'hospital_services': 'மருத்துவமனை சேவைகள்',
      'hospital_map': 'மருத்துவமனை வரைபடம்',
      'finish_print_ticket': 'பதிவை முடித்து சீட்டு பெறவும்',

      // Completion
      'completion_title': 'பதிவு வெற்றிகரமாக முடிந்தது!',
      'completion_sub': 'உங்கள் விவரங்கள் மருத்துவர் அறை 102-க்கு அனுப்பப்பட்டுள்ளன.',
      'opd_ticket_issued': 'OPD டோக்கன் வழங்கப்பட்டது',
      'auto_reset_title': 'தனியுரிமை தானியங்கி அழிப்பு',
      'auto_reset_sub': 'உங்கள் தகவல்களைப் பாதுகாக்க இந்த திரை தானாக அழிக்கப்படும் நேரம்:',
      'reset_now': 'உடனே முடிக்கவும்',
      'keep_open': 'திறந்தே வைக்கவும்',
      'reset_button': 'முடிக்கவும்',

      // Triage & Emergency
      'emergency_title': 'அவசர சிகிச்சை தேவை',
      'emergency_alert_staff': 'மருத்துவ பணியாளருக்கு தெரிவிக்கவும்',
      'triage_alert_title': 'அவசர சிகிச்சை எச்சரிக்கை',
      'triage_alert_sub': 'உங்கள் அறிகுறிகளுக்கு உடனடி மருத்துவர் உதவி தேவை. பொது வரிசையில் காத்திருக்க வேண்டாம்.',
      'triage_steps_title': 'உடனே செய்ய வேண்டியவை:',
      'triage_step_1': 'அமைதியாக அமரவும், நடப்பதைத் தவிர்க்கவும்.',
      'triage_step_2': 'இந்த திரையை அறை 1 (அவசர பிரிவு)-ல் காட்டவும்.',
      'triage_step_3': 'உங்கள் டோக்கன் அவசர முன்னுரிமை (RED) பெற்றுள்ளது.',
      'go_emergency_room': 'உடனே அவசர சிகிச்சைப் பிரிவுக்குச் செல்லவும்',
      'continue_routine_intake': 'வழக்கமான பதிவைத் தொடரவும்',
      'immediate_emergency_help': 'உடனடி அவசர சிகிச்சை உதவி',
      'immediate_emergency_sub': 'கடுமையான நெஞ்சு வலி அல்லது மயக்கம் இருந்தால் உடனடியாக உதவி பெறவும்.',
      'casualty_line': 'அவசர உதவி எண்: 011-2999-4444 (அல்லது 108)',
      'ambulance_dispatch_btn': 'ஆம்புலன்ஸ் அழைக்கவும்',
      'return_to_intake': 'திரும்பிச் செல்லவும்',
      'ambulance_dispatched_title': 'ஆம்புலன்ஸ் புறப்பட்டுவிட்டது',
      'ambulance_dispatched_sub': 'வாகனம் அவசர வாயிலை நோக்கி வந்துகொண்டிருக்கிறது.',
      'estimated_arrival': 'வந்து சேரும் நேரம்',

      // Services & Map
      'hospital_services_title': 'மருத்துவமனை சேவைகள்',
      'hospital_services_sub': 'முக்கிய கவுண்டர்கள் மற்றும் காத்திருப்பு நேரங்கள்.',
      'hospital_map_title': 'மருத்துவமனை வரைபடம்',
      'hospital_map_sub': 'மருத்துவர் அறைகளுக்கான வழிகாட்டி வரைபடம்.',
      'pharmacy_title': 'மருந்தகம் (Pharmacy)',
      'pathology_title': 'பரிசோதனை கூடம் (Lab)',
      'injection_title': 'ஊசி மற்றும் கட்டு அறை',
      'radiology_title': 'எக்ஸ்-ரே பிரிவு (Radiology)',
      'ayush_dispensary_title': 'ஆயுஷ் மூலிகை மருந்தகம்',

      // Call intake
      'active_call_title': 'செயலில் உள்ள AI அழைப்பு',
      'ai_doctor_speaking': 'AI மருத்துவர் பேசுகிறார்...',
      'listening_for_symptoms': 'உங்கள் அறிகுறிகளைக் கேட்கிறோம்... பேசவும்...',
      'tap_symptoms_quiet_mic': 'மைக் வேலை செய்யாவிட்டால் அறிகுறிகளைத் தட்டவும்:',
    },

    'te': {
      // Welcome
      'welcome_title': 'మెడికియోస్క్‌కు స్వాగతం',
      'welcome_subtitle': 'వాయిస్ ఆధారిత వేగవంతమైన ఓపీడీ నమోదు',
      'start_button': 'ప్రారంభించండి',
      'emergency_assistance_btn': 'అత్యవసరమా? సహాయం కోసం ఇక్కడ నొక్కండి',
      'voice_call_fast_track_title': '1-ట్యాప్ వాయిస్ కాల్',
      'voice_call_fast_track_sub': 'ఫారమ్‌లు లేకుండా నేరుగా AI వైద్యుడితో మాట్లాడండి',
      'helpline_card_title': '2G టోల్-ఫ్రీ ఫోన్ నమోదు',
      'helpline_card_sub': 'కీప్యాడ్ ఫోన్ల కోసం: 1800-890-AYUSH కు డయల్ చేయండి (ఉచితం, ఇంటర్నెట్ అవసరం లేదు)',
      'clear': 'తొలగించు',

      // Language Selection
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'choose_language_sub': 'మీరు సౌకర్యవంతంగా మాట్లాడటానికి మరియు చదవడానికి భాషను ఎంచుకోండి',

      // Consent
      'consent_title': 'రోగి సమ్మతి & గోప్యతా నోటీసు',
      'consent_body': 'మీ వైద్యుడికి సహాయపడటానికి మీ వివరాలు మరియు రిపోర్టులు సేకరించబడుతున్నాయి. మీ డేటా పూర్తిగా సురక్షితం.',
      'audio_explanation_title': 'ఆడియో వివరణ',
      'audio_explanation_sub': 'నిబంధనలు వినడానికి ఇక్కడ నొక్కండి',
      'playing_notice': 'తెలుగులో నిబంధనలు వినిపిస్తున్నాయి...',
      'dpdp_bullet': 'డిజిటల్ వ్యక్తిగత డేటా రక్షణ చట్టం క్రింద రక్షించబడింది.',
      'doctor_use_bullet': 'ఈ సంప్రదింపులో మీ వైద్యుడికి మాత్రమే చూపబడుతుంది.',
      'auto_purge_bullet': 'ఆడియో రికార్డింగ్‌లు మరియు పత్రాలు స్వయంచాలకంగా తొలగించబడతాయి.',
      'agree_continue': 'నేను అంగీకరిస్తున్నాను',
      'decline_exit': 'తిరస్కరించి నిష్క్రమించు',

      // Identity
      'identify_title': 'రోగి గుర్తింపు',
      'identify_sub': 'పాత రికార్డుల కోసం ABHA QR స్కాన్ చేయండి లేదా మొబైల్ నంబర్ నమోదు చేయండి.',
      'scan_abha': 'ABHA QR కోడ్‌ను స్కాన్ చేయండి',
      'hold_card_camera': 'హెల్త్ కార్డును కెమెరా ముందు ఉంచండి',
      'open_qr_scanner': 'QR స్కానర్ తెరవండి',
      'enter_mobile': 'లేదా 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
      'verify_phone': 'ఫోన్ ధృవీకరించండి',
      'skip_identify': 'దాటవేసి కొనసాగండి (అతిథిగా)',

      // Care Stream
      'care_stream_title': 'విభాగాన్ని ఎంచుకోండి',
      'care_stream_sub': 'ఈరోజు మీరు ఏ విభాగాన్ని సంప్రదించాలనుకుంటున్నారు?',
      'general_medicine_title': 'జనరల్ మెడిసిన్ (సాధారణ విభాగం)',
      'general_medicine_sub': 'జ్వరం, దగ్గు, బలహీనత, రక్తపోటు, మధుమేహం',
      'ayush_dept_title': 'ఆయుష్ & ఆయుర్వేదం',
      'ayush_dept_sub': 'కీళ్ల నొప్పులు, జీర్ణ సమస్యలు, ప్రకృతి, జీవనశైలి',
      'pediatrics_dept_title': 'పిల్లల వైద్య విభాగం',
      'pediatrics_dept_sub': 'టీకాలు, పిల్లల ఎదుగుదల, ఇన్ఫెక్షన్లు',
      'emergency_dept_title': 'అత్యవసర విభాగం',
      'emergency_dept_sub': 'ఛాతీ నొప్పి, తీవ్రమైన శ్వాస సమస్య, గాయాలు',
      'continue_intake': 'లక్షణాల నమోదుకు కొనసాగండి',
      'continue_ayush_intake': 'ఆయుష్ నమోదును ప్రారంభించండి',
      'continue_emergency_triage': 'తక్షణ అత్యవసర సహాయం',

      // Voice Intake & Active Capture
      'voice_intake_title': 'మీ సమస్యలను మాట్లాడి చెప్పండి',
      'tap_to_speak': 'మాట్లాడటానికి నొక్కండి',
      'listening': 'వింటున్నాము... చెప్పండి',
      'speak_clearly_mic': 'మైక్ దగ్గర స్పష్టంగా మాట్లాడండి',
      'tap_wave_resume': 'మళ్లీ మాట్లాడటానికి నొక్కండి',
      'speech_symptom_input': 'మాట్లాడిన లక్షణాలు:',
      'tap_symptom_chip_prompt': 'లేదా క్రింది లక్షణాలపై నొక్కండి:',
      'type_or_select_hint': 'ఇక్కడ టైప్ చేయండి లేదా ఎంచుకోండి...',
      'done_speaking': 'మాట్లాడటం పూర్తయింది',
      'type_symptoms_link': 'టైప్ చేయాలనుకుంటున్నారా? ఇక్కడ నొక్కండి',
      'call_intake_shortcut_title': 'AI డాక్టర్‌తో ఫోన్ కాల్‌లో మాట్లాడండి',
      'call_intake_shortcut_btn': 'AI కాల్ ప్రారంభించండి',
      'describe_symptoms_title': 'మీ లక్షణాలను వివరించండి',
      'describe_symptoms_sub': 'క్రింద మీ ఆరోగ్య సమస్యలను టైప్ చేయండి లేదా లక్షణాలను ఎంచుకోండి.',
      'submit_and_analyze': 'లక్షణాలను సమర్పించి విశ్లేషించండి',
      'switch_to_voice': 'వాయిస్ ఇన్‌టేక్‌కు మారండి',
      'describe_symptoms_hint': 'మీ లక్షణాలను ఇక్కడ నమోదు చేయండి...',

      // Chips
      'chip_fever': 'జ్వరం',
      'chip_headache': 'తీవ్రమైన తలనొప్పి',
      'chip_cough': 'దగ్గు మరియు జలుబు',
      'chip_stomach_pain': 'కడుపు నొప్పి',
      'chip_joint_pain': 'కీళ్ల నొప్పులు',
      'chip_chest_pain': 'ఛాతీ నొప్పి',
      'chip_vomiting': 'వాంతులు లేదా వికారం',
      'chip_back_pain': 'నడుము లేదా వీపు నొప్పి',
      'chip_breathlessness': 'శ్వాస తీసుకోవడంలో ఇబ్బంది',
      'chip_dizziness': 'తలతిరగడం',

      // Followup
      'followup_title': 'అదనపు ప్రశ్న',
      'followup_sub': 'వైద్యుడికి స్పష్టంగా అర్థం కావడానికి దయచేసి ఈ ప్రశ్నకు సమాధానం ఇవ్వండి.',
      'confirm_answer': 'సమాధానాన్ని నిర్ధారించండి',
      'skip_to_summary': 'నేరుగా సారాంశానికి వెళ్లండి',

      // Processing
      'processing': 'విశ్లేషిస్తున్నాము...',
      'processing_sub': 'వైద్య వివరాలను పరిశీలిస్తున్నాము...',

      // Summary
      'summary_title': 'దయచేసి వివరాలను ధృవీకరించండి',
      'summary_sub': 'ప్రతి అంశాన్ని తనిఖీ చేయండి. నిర్ధారించడానికి "సరైనది" లేదా "తప్పు" నొక్కండి.',
      'no_symptoms_title': 'లక్షణాలు ఏవీ ఇంకా నమోదు కాలేదు',
      'no_symptoms_sub': 'మాట్లాడటానికి లేదా టైప్ చేయడానికి క్రింది బటన్ నొక్కండి.',
      'confirm_yes': 'అవును, సరైనది',
      'confirm_no': 'కాదు, మార్చండి',
      'confirm_next': 'ధృవీకరించి కొనసాగండి',
      'add_another_symptom': '+ మరొక లక్షణం జోడించండి',
      'verified_badge': 'ధృవీకరించబడింది',
      'patient_said': 'రోగి చెప్పినది:',

      // Documents
      'doc_scan_title': 'పాత ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
      'doc_scan_sub': 'పాత ప్రిస్క్రిప్షన్ స్కాన్ చేయడం వల్ల మీ మునుపటి మందులు వైద్యుడికి తెలుస్తాయి.',
      'doc_prescription_check': 'డాక్టర్ ప్రిస్క్రిప్షన్',
      'doc_lab_check': 'రక్తం, మూత్ర పరీక్ష రిపోర్టులు',
      'doc_discharge_check': 'ఆసుపత్రి డిశ్చార్జ్ సమ్మరీ',
      'scan_doc_btn': 'పత్రాన్ని స్కాన్ చేయండి',
      'no_doc_btn': 'పత్రాలు లేవు / కొనసాగండి',
      'extracted_meds_title': 'ప్రిస్క్రిప్షన్ నుండి గుర్తించిన మందులు',
      'extracted_meds_sub': 'మీ పత్రం నుండి సేకరించిన మందులు. ఇవి సరైనవేనా సరిచూసుకోండి.',
      'confirm_continue_meds': 'మందులు సరైనవి, కొనసాగండి',
      'inspect_source_doc': 'అసలు పత్రాన్ని చూడండి',

      // Vitals
      'vitals_title': 'శరీర కొలతలు (Vitals)',
      'vitals_sub': 'సెన్సార్ లేదా నర్సింగ్ స్టేషన్ ద్వారా నమోదు చేయబడిన వివరాలు.',
      'confirm_vitals_next': 'కొలతలను నిర్ధారించి కొనసాగండి',
      'bp_label': 'రక్తపోటు (BP)',
      'hr_label': 'నాడి వేగం (Heart Rate)',
      'spo2_label': 'ఆక్సిజన్ స్థాయి (SpO2)',
      'temp_label': 'శరీర ఉష్ణోగ్రత',
      'sugar_label': 'బ్లడ్ షుగర్',
      'normal_status': 'సాధారణం',

      // AYUSH
      'ayush_title': 'ఆయుష్ పరీక్ష (దశవిధ పరీక్ష)',
      'ayush_sub': 'మీ ఆయుర్వేద వైద్యుడి కోసం ముందస్తు అంచనా.',
      'agni_section_title': '1. జీర్ణ శక్తి (అగ్ని)',
      'sama_agni': 'సమ అగ్ని',
      'sama_agni_sub': 'సమతుల్య ఆకలి, సాధారణ జీర్ణం',
      'vishama_agni': 'విషమ అగ్ని',
      'vishama_agni_sub': 'అస్థిరమైన జీర్ణం, గ్యాస్, కడుపుబ్బరం',
      'tikshna_agni': 'తీక్ష్ణ అగ్ని',
      'tikshna_agni_sub': 'అధిక ఆకలి, గుండెల్లో మంట, చాలా వేగవంతమైన జీర్ణం',
      'manda_agni': 'మంద అగ్ని',
      'manda_agni_sub': 'మందగించిన జీర్ణం, తిన్న తర్వాత బరువుగా అనిపించడం',
      'ama_section_title': 'విషతుల్య పదార్థాలు (ఆమ లక్షణాలు)',
      'coated_tongue': 'నాలుకపై తెల్లటి లేదా పసుపు పూత',
      'morning_stiffness': 'ఉదయం శరీరంలో బరువు లేదా కీళ్ల బిగుతు',
      'prakriti_section_title': '2. శరీర ప్రకృతి',
      'tridoshaja_title': 'త్రిదోషజ (సమతుల్య ప్రకృతి)',
      'tridoshaja_sub': 'సమతుల్య శరీరం, మంచి నిద్ర, రోగనిరోధక శక్తి',
      'vata_title': 'వాత ప్రధానం',
      'vata_sub': 'సన్నని శరీరం, పొడి చర్మం, చలిని తట్టుకోలేకపోవడం',
      'pitta_title': 'పిత్త ప్రధానం',
      'pitta_sub': 'మధ్యస్థ శరీరం, వేడి చర్మం, వేడిని తట్టుకోలేకపోవడం',
      'kapha_title': 'కఫ ప్రధానం',
      'kapha_sub': 'ధృడమైన శరీరం, ప్రశాంతమైన మనస్తత్వం, గాఢ నిద్ర',
      'koshtha_section_title': '3. మలవిసర్జన తీరు (కోష్ఠం)',
      'madhyama_koshtha': 'మధ్యమ కోష్ఠం (క్రమమైన విసర్జన)',
      'krura_koshtha': 'క్రూర కోష్ఠం (మలబద్ధకం, కఠిన మలం)',
      'mridu_koshtha': 'మృదు కోష్ఠం (సులభంగా విరేచనాలు కావడం)',
      'continue_queue': 'ఆయుష్ వివరాలు నమోదు చేసి టోకెన్ తీసుకోండి',

      // Queue
      'queue_title': 'మీ టోకెన్ సంఖ్య',
      'your_queue_token': 'మీ టోకెన్ సంఖ్య',
      'patients_ahead': 'ముందున్న రోగులు',
      'est_wait': 'వేచి ఉండే సమయం',
      'hospital_services': 'ఆసుపత్రి సేవలు',
      'hospital_map': 'ఆసుపత్రి మ్యాప్',
      'finish_print_ticket': 'నమోదు ముగించి రశీదు తీసుకోండి',

      // Completion
      'completion_title': 'నమోదు విజయవంతంగా పూర్తయింది!',
      'completion_sub': 'మీ వివరాలు వైద్యుడి గది 102కి పంపబడ్డాయి.',
      'opd_ticket_issued': 'OPD టోకెన్ జారీ చేయబడింది',
      'auto_reset_title': 'గోప్యతా ఆటో-రీసెట్',
      'auto_reset_sub': 'మీ సమాచారాన్ని రక్షించడానికి ఈ స్క్రీన్ స్వయంచాలకంగా రీసెట్ అవుతుంది:',
      'reset_now': 'ఇప్పుడే ముగించండి',
      'keep_open': 'తెరచి ఉంచండి',
      'reset_button': 'ముగించండి',

      // Triage & Emergency
      'emergency_title': 'అత్యవసర చికిత్స అవసరం',
      'emergency_alert_staff': 'సిబ్బందికి సమాచారం ఇవ్వండి',
      'triage_alert_title': 'అత్యవసర హెచ్చరిక (రెడ్ అలర్ట్)',
      'triage_alert_sub': 'మీ లక్షణాలకు తక్షణ వైద్య సహాయం అవసరం. సాధారణ క్యూలో వేచి ఉండకండి.',
      'triage_steps_title': 'వెంటనే చేయవలసినవి:',
      'triage_step_1': 'ప్రశాంతంగా కూర్చోండి, శ్రమించవద్దు.',
      'triage_step_2': 'ఈ స్క్రీన్‌ను గది 1 (ఎమర్జెన్సీ) వద్ద చూపించండి.',
      'triage_step_3': 'మీ టోకెన్‌కు అత్యవసర ప్రాధాన్యత (RED) ఇవ్వబడింది.',
      'go_emergency_room': 'నేరుగా ఎమర్జెన్సీ గదికి వెళ్లండి',
      'continue_routine_intake': 'సాధారణ ప్రక్రియను కొనసాగించండి',
      'immediate_emergency_help': 'తక్షణ అత్యవసర సహాయం',
      'immediate_emergency_sub': 'తీవ్రమైన ఛాతీ నొప్పి లేదా అపస్మారక స్థితి ఉంటే వెంటనే సహాయం పొందండి.',
      'casualty_line': 'అత్యవసర సహాయ ఫోన్: 011-2999-4444 (లేదా 108)',
      'ambulance_dispatch_btn': 'అంబులెన్స్ పిలవండి',
      'return_to_intake': 'వెనక్కి వెళ్ళండి',
      'ambulance_dispatched_title': 'అంబులెన్స్ బయలుదేరింది',
      'ambulance_dispatched_sub': 'వాహనం ఆసుపత్రి ఎమర్జెన్సీ గేట్ వైపు వస్తోంది.',
      'estimated_arrival': 'చేరుకునే సమయం',

      // Services & Map
      'hospital_services_title': 'ఆసుపత్రి సేవలు',
      'hospital_services_sub': 'ముఖ్యమైన కౌంటర్లు మరియు వేచి ఉండే సమయాలు.',
      'hospital_map_title': 'ఆసుపత్రి మ్యాప్ & దిశలు',
      'hospital_map_sub': 'డాక్టర్ గదులకు చేరుకోవడానికి గైడ్.',
      'pharmacy_title': 'మందుల దుకాణం (Pharmacy)',
      'pathology_title': 'ల్యాబ్ పరీక్షలు (Pathology)',
      'injection_title': 'ఇంజెక్షన్ & డ్రెస్సింగ్ రూమ్',
      'radiology_title': 'ఎక్స్-రే & రేడియాలజీ',
      'ayush_dispensary_title': 'ఆయుష్ ఔషధాల కౌంటర్',

      // Call intake
      'active_call_title': 'AI డాక్టర్ కాల్',
      'ai_doctor_speaking': 'AI డాక్టర్ మాట్లాడుతున్నారు...',
      'listening_for_symptoms': 'మీ లక్షణాలు వింటున్నాము... మాట్లాడండి...',
      'tap_symptoms_quiet_mic': 'మైక్ పని చేయకపోతే లక్షణాలపై నొక్కండి:',
    },

    'mr': {
      // Welcome
      'welcome_title': 'मेडीकिओस्क मध्ये आपले स्वागत आहे',
      'welcome_subtitle': 'जलद, बोलून लक्षणे नोंदवण्याची ओपीडी सुविधा',
      'start_button': 'सुरू करा',
      'emergency_assistance_btn': 'तातडीची मदत हवी आहे का? येथे दाबा',
      'voice_call_fast_track_title': '१-टॅप व्हॉइस कॉल',
      'voice_call_fast_track_sub': 'फॉर्म न भरता थेट AI डॉक्टरांशी बोलून सांगा',
      'helpline_card_title': '2G टोल-फ्री फोन नोंदणी',
      'helpline_card_sub': 'कीपॅड फोनसाठी: 1800-890-AYUSH डायल करा (विनामूल्य, इंटरनेटची गरज नाही)',
      'clear': 'हटवा',

      // Language Selection
      'select_language': 'आपली भाषा निवडा',
      'choose_language_sub': 'आपल्या सोयीची भाषा निवडा ज्यामध्ये आपण बोलू व वाचू शकता',

      // Consent
      'consent_title': 'रुग्ण संमती व गोपनीयता माहिती',
      'consent_body': 'डॉक्टरांच्या मदतीसाठी आपली लक्षणे व कागदपत्रे सुरक्षितपणे नोंदवली जातात. आपली माहिती पूर्णपणे सुरक्षित आहे.',
      'audio_explanation_title': 'ऑडिओ माहिती',
      'audio_explanation_sub': 'गोपनीयता नियम ऐकण्यासाठी येथे दाबा',
      'playing_notice': 'मराठीत माहिती ऐकवली जात आहे...',
      'dpdp_bullet': 'डिजिटल वैयक्तिक डेटा संरक्षण कायद्यांतर्गत सुरक्षित.',
      'doctor_use_bullet': 'फक्त आपल्या तपासणी करणाऱ्या डॉक्टरांनाच दाखवली जाईल.',
      'auto_purge_bullet': 'ऑडिओ रेकॉर्डिंग व कागदपत्रे आपोआप नष्ट केली जातात.',
      'agree_continue': 'मी सहमत आहे आणि पुढे जा',
      'decline_exit': 'नाकारून बाहेर पडा',

      // Identity
      'identify_title': 'रुग्ण ओळख',
      'identify_sub': 'मागील वैद्यकीय नोंदी मिळवण्यासाठी आभा QR किंवा मोबाईल नंबर टाका.',
      'scan_abha': 'आभा (ABHA) क्यूआर कोड स्कॅन करा',
      'hold_card_camera': 'कार्ड कॅमेऱ्यासमोर धरा',
      'open_qr_scanner': 'QR स्कॅनर उघडा',
      'enter_mobile': 'किंवा १०-अंकी मोबाईल नंबर टाका',
      'verify_phone': 'नंबर तपासा',
      'skip_identify': 'ओळख वगळा (Skip)',

      // Care Stream
      'care_stream_title': 'विभागाची निवड करा',
      'care_stream_sub': 'आज आपण कोणत्या विभागात डॉक्टरांचा सल्ला घेऊ इच्छिता?',
      'general_medicine_title': 'सामान्य औषधोपचार (General Medicine)',
      'general_medicine_sub': 'ताप, खोकला, सर्दी, अशक्तपणा, बीपी, मधुमेह',
      'ayush_dept_title': 'आयुष व आयुर्वेद',
      'ayush_dept_sub': 'सांधेदुखी, पचन समस्या, प्रकृती, जीवनशैली',
      'pediatrics_dept_title': 'बालरोग विभाग',
      'pediatrics_dept_sub': 'लहान मुलांचे लसीकरण, वाढ, संसर्ग',
      'emergency_dept_title': 'तातडीचे उपचार (इमर्जन्सी)',
      'emergency_dept_sub': 'छातीत दुखणे, धाप लागणे, गंभीर दुखापत',
      'continue_intake': 'लक्षणे सांगण्यासाठी पुढे जा',
      'continue_ayush_intake': 'आयुष तपासणी सुरू करा',
      'continue_emergency_triage': 'तातडीची मदत मिळवा',

      // Voice Intake & Active Capture
      'voice_intake_title': 'आपला त्रास बोलून सांगा',
      'tap_to_speak': 'बोलण्यासाठी माइक दाबा',
      'listening': 'आम्ही ऐकत आहोत... बोला',
      'speak_clearly_mic': 'कृपया माइक जवळ स्पष्ट आवाजात बोला',
      'tap_wave_resume': 'पुन्हा बोलण्यासाठी माइक दाबा',
      'speech_symptom_input': 'सांगितलेली लक्षणे:',
      'tap_symptom_chip_prompt': 'किंवा खालीलपैकी लक्षणे निवडा:',
      'type_or_select_hint': 'येथे टाईप करा किंवा खालील लक्षणे निवडा...',
      'done_speaking': 'बोलणे पूर्ण झाले',
      'type_symptoms_link': 'टाईप करू इच्छिता? येथे दाबा',
      'call_intake_shortcut_title': 'AI डॉक्टरांशी फोन कॉलवर बोला',
      'call_intake_shortcut_btn': 'AI कॉल सुरू करा',
      'describe_symptoms_title': 'तुमची लक्षणे सांगा',
      'describe_symptoms_sub': 'खाली तुमच्या तक्रारी टाईप करा किंवा सामान्य लक्षणे निवडा.',
      'submit_and_analyze': 'लक्षणे नोंदवा आणि विश्लेषण करा',
      'switch_to_voice': 'बोलून सांगण्यावर स्विच करा',
      'describe_symptoms_hint': 'येथे तुमची लक्षणे लिहा...',

      // Chips
      'chip_fever': 'ताप',
      'chip_headache': 'तीव्र डोकेदुखी',
      'chip_cough': 'खोकला आणि सर्दी',
      'chip_stomach_pain': 'पोटदुखी',
      'chip_joint_pain': 'सांधेदुखी',
      'chip_chest_pain': 'छातीत दुखणे',
      'chip_vomiting': 'उलटी किंवा मळमळ',
      'chip_back_pain': 'कंबरदुखी किंवा पाठदुखी',
      'chip_breathlessness': 'श्वास घेण्यास त्रास',
      'chip_dizziness': 'चक्कर येणे',

      // Followup
      'followup_title': 'पुढील प्रश्न',
      'followup_sub': 'डॉक्टरांच्या अचूक समजुतीसाठी कृपया या प्रश्नाचे उत्तर द्या.',
      'confirm_answer': 'उत्तर निश्चित करा',
      'skip_to_summary': 'थेट सारांशावर जा',

      // Processing
      'processing': 'माहिती समजून घेत आहोत...',
      'processing_sub': 'वैद्यकीय माहितीची तपासणी सुरू आहे...',

      // Summary
      'summary_title': 'कृपया आम्ही समजलेली माहिती तपासा',
      'summary_sub': 'प्रत्येक लक्षण तपासा. खात्रीसाठी "बरोबर आहे" किंवा "चूक आहे" दाबा.',
      'no_symptoms_title': 'अद्याप कोणतीही लक्षणे नोंदवली गेली नाहीत',
      'no_symptoms_sub': 'बोलून किंवा टाईप करून लक्षणे नोंदवण्यासाठी खालील बटण दाबा.',
      'confirm_yes': 'होय, बरोबर आहे',
      'confirm_no': 'नाही, चूक आहे',
      'confirm_next': 'माहिती निश्चित करा व पुढे जा',
      'add_another_symptom': '+ आणखी लक्षण जोडा',
      'verified_badge': 'सत्यापित',
      'patient_said': 'रुग्णाने सांगितले:',

      // Documents
      'doc_scan_title': 'जुने प्रिस्क्रिप्शन किंवा अहवाल स्कॅन करा',
      'doc_scan_sub': 'जुने प्रिस्क्रिप्शन स्कॅन केल्याने आधीची औषधे डॉक्टरांना दिसतात.',
      'doc_prescription_check': 'डॉक्टरांची जुनी चिठ्ठी',
      'doc_lab_check': 'रक्त व लघवी तपासणी अहवाल',
      'doc_discharge_check': 'डिस्चार्ज समरी',
      'scan_doc_btn': 'कागदपत्र स्कॅन करा',
      'no_doc_btn': 'कागदपत्र नाही / पुढे जा',
      'extracted_meds_title': 'प्रिस्क्रिप्शनमधून मिळालेली औषधे',
      'extracted_meds_sub': 'कागदपत्रातून ओळखलेली औषधे. ही आपलीच औषधे आहेत का ते तपासा.',
      'confirm_continue_meds': 'औषधे बरोबर आहेत, पुढे जा',
      'inspect_source_doc': 'मूळ कागदपत्र पहा',

      // Vitals
      'vitals_title': 'शारीरिक तपासणी (Vitals)',
      'vitals_sub': 'कियोस्क सेन्सर किंवा नर्सिंग स्टेशनद्वारे घेतलेली मोजमापे.',
      'confirm_vitals_next': 'तपासणी निश्चित करा व पुढे जा',
      'bp_label': 'रक्तदाब (Blood Pressure)',
      'hr_label': 'नाडीचे ठोके (Heart Rate)',
      'spo2_label': 'ऑक्सिजन पातळी (SpO2)',
      'temp_label': 'शरीराचे तापमान',
      'sugar_label': 'ब्लड शुगर',
      'normal_status': 'सामान्य',

      // AYUSH
      'ayush_title': 'आयुर्वेदिक प्रकृती व अग्नी तपासणी',
      'ayush_sub': 'आपल्या आयुर्वेदिक डॉक्टरांसाठी दशविध परीक्षा पूर्व-मूल्यांकन.',
      'agni_section_title': '१. पचनशक्ती (अग्नी)',
      'sama_agni': 'सम अग्नी',
      'sama_agni_sub': 'संतुलित भूक, त्रास न होता पचन',
      'vishama_agni': 'विषम अग्नी',
      'vishama_agni_sub': 'अनियमित पचन, गॅस, पोट फुगणे, भूकेत चढ-उतार',
      'tikshna_agni': 'तीक्ष्ण अग्नी',
      'tikshna_agni_sub': 'खूप भूक लागणे, छातीत जळजळ, अतिशय जलद पचन',
      'manda_agni': 'मन्द अग्नी',
      'manda_agni_sub': 'मंद पचन, जेवणानंतर जड वाटणे, कमी भूक',
      'ama_section_title': 'आम लक्षणे (विषारी घटक)',
      'coated_tongue': 'जिभेवर पांढरा किंवा पिवळा थर',
      'morning_stiffness': 'सकाळी अंग जड वाटणे किंवा सांधे आखडणे',
      'prakriti_section_title': '२. शारीरिक प्रकृती',
      'tridoshaja_title': 'त्रिदोषज (संतुलित प्रकृती)',
      'tridoshaja_sub': 'संतुलित शरीर, शांत झोप, उत्तम प्रतिकारशक्ती',
      'vata_title': 'वात प्रधान',
      'vata_sub': 'सडपातळ शरीर, कोरडी त्वचा, हलकी झोप, थंडी सहन न होणे',
      'pitta_title': 'पित्त प्रधान',
      'pitta_sub': 'मध्यम शरीर, उष्ण त्वचा, तीव्र भूक, उष्णता सहन न होणे',
      'kapha_title': 'कफ प्रधान',
      'kapha_sub': 'मजबूत शरीर, शांत स्वभाव, गाढ झोप, थंड त्वचा',
      'koshtha_section_title': '३. कोष्ठ (पोट साफ होण्याची सवय)',
      'madhyama_koshtha': 'मध्यम कोष्ठ (नियमित पोट साफ होणे)',
      'krura_koshtha': 'क्रूर कोष्ठ (बद्धकोष्ठता, कडक शौच)',
      'mridu_koshtha': 'मृदू कोष्ठ (सहज जुलाब होणे, संवेदनशील पोट)',
      'continue_queue': 'माहिती नोंदवून टोकन मिळवा',

      // Queue
      'queue_title': 'आपला ओपीडी टोकन क्रमांक',
      'your_queue_token': 'आपला टोकन क्रमांक',
      'patients_ahead': 'तुमच्या आधीचे रुग्ण',
      'est_wait': 'अंदाजे वेळ',
      'hospital_services': 'रुग्णालय सेवा व औषधालय',
      'hospital_map': 'रुग्णालयाचा नकाशा',
      'finish_print_ticket': 'नोंदणी संपवा व पावती घ्या',

      // Completion
      'completion_title': 'नोंदणी यशस्वीपणे पूर्ण झाली!',
      'completion_sub': 'आपली माहिती रूम नंबर १०२ कडे पाठवण्यात आली आहे.',
      'opd_ticket_issued': 'OPD टोकन दिले गेले',
      'auto_reset_title': 'गोपनीयता स्वयं-रीसेट',
      'auto_reset_sub': 'आपली माहिती सुरक्षित ठेवण्यासाठी ही स्क्रीन आपोआप रीसेट होईल:',
      'reset_now': 'आत्ताच समाप्त करा',
      'keep_open': 'उघडे ठेवा',
      'reset_button': 'समाप्त करा (Reset)',

      // Triage & Emergency
      'emergency_title': 'तातडीच्या उपचारांची आवश्यकता',
      'emergency_alert_staff': 'ओपीडी नर्सला ताबडतोब कळवा',
      'triage_alert_title': 'तातडीचा इशारा (रेड अलर्ट)',
      'triage_alert_sub': 'आपल्या लक्षणांना तातडीच्या उपचारांची गरज आहे. सामान्य रांगेत थांबू नका.',
      'triage_steps_title': 'आत्ताच काय करावे:',
      'triage_step_1': 'शांत बसा आणि जास्त हालचाल करू नका.',
      'triage_step_2': 'ही स्क्रीन रूम नंबर १ (इमर्जन्सी) मध्ये दाखवा.',
      'triage_step_3': 'आपल्या टोकनला तातडीचे प्राधान्य (RED) दिले गेले आहे.',
      'go_emergency_room': 'थेट इमर्जन्सी रूममध्ये जा',
      'continue_routine_intake': 'सामान्य प्रक्रिया सुरू ठेवा',
      'immediate_emergency_help': 'तातडीची वैद्यकीय मदत',
      'immediate_emergency_sub': 'छातीत तीव्र दुखणे किंवा बेशुद्ध पडत असल्यास ताबडतोब मदत घ्या.',
      'casualty_line': 'इमर्जन्सी फोन: 011-2999-4444 (किंवा 108 वर कॉल करा)',
      'ambulance_dispatch_btn': 'रुग्णवाहिका बोलवा',
      'return_to_intake': 'परत जा',
      'ambulance_dispatched_title': 'रुग्णवाहिका रवाना झाली आहे',
      'ambulance_dispatched_sub': 'गाडी रुग्णालयाच्या इमर्जन्सी गेटकडे येत आहे.',
      'estimated_arrival': 'पोहोचण्याची अंदाजे वेळ',

      // Services & Map
      'hospital_services_title': 'रुग्णालय सेवा व काऊंटर्स',
      'hospital_services_sub': 'महत्त्वाचे काऊंटर्स आणि प्रतीक्षा वेळ.',
      'hospital_map_title': 'रुग्णालयाचा नकाशा व दिशा',
      'hospital_map_sub': 'तपासणी रूमपर्यंत जाण्यासाठी मार्गदर्शन.',
      'pharmacy_title': 'औषधालय (Pharmacy)',
      'pathology_title': 'पॅथॉलॉजी व रक्त तपासणी लॅब',
      'injection_title': 'इंजेक्शन व ड्रेसिंग रूम',
      'radiology_title': 'रेडिओलॉजी व एक्स-रे',
      'ayush_dispensary_title': 'आयुष औषध वितरण केंद्र',

      // Call intake
      'active_call_title': 'सक्रिय AI डॉक्टर कॉल',
      'ai_doctor_speaking': 'AI डॉक्टर बोलत आहेत...',
      'listening_for_symptoms': 'आम्ही ऐकत आहोत... कृपया बोला...',
      'tap_symptoms_quiet_mic': 'माइक चालत नसेल तर लक्षणे निवडा:',
    },
  };
}
