import 'package:flutter/material.dart';

/// Language state provider with native Indian language localization strings
/// Supports: English, Hindi, Tamil, Telugu, Marathi
/// Ref: MEDIKIOSK_ANDROID_DESIGN_SPEC.md Section 3
class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'hi'; // Default Hindi for North/Central AIIMS/AIIA OPDs

  String get currentLanguage => _currentLanguage;

  void setLanguage(String langCode) {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      notifyListeners();
    }
  }

  // Common UI Localization Dictionary
  String translate(String key) {
    final translations = _localizedStrings[_currentLanguage] ?? _localizedStrings['en']!;
    return translations[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'welcome_title': 'Welcome to MediKiosk',
      'welcome_subtitle': 'Fast, Voice-Powered OPD Pre-Consultation Intake',
      'start_button': 'START INTAKE (शुरू करें)',
      'select_language': 'Select Your Language',
      'consent_title': 'Patient Consent & Privacy Notice',
      'consent_body':
          'MediKiosk collects your symptoms and documents to assist your OPD doctor. Your information is protected under the Digital Personal Data Protection Act and will never be shared without consent.',
      'agree_continue': 'I AGREE & CONTINUE (सहमत हैं)',
      'identify_title': 'Patient Identification',
      'scan_abha': 'Scan ABHA QR Code',
      'enter_mobile': 'Or Enter 10-Digit Mobile Number',
      'skip_identify': 'SKIP & PROCEED AS GUEST',
      'care_stream_title': 'Select Reason for Visit',
      'voice_intake_title': 'Tell Us What Is Bothering You',
      'tap_to_speak': 'TAP TO SPEAK (बोलने के लिए दबाएं)',
      'listening': 'Listening... हम सुन रहे हैं',
      'processing': 'Understanding Symptoms...',
      'summary_title': 'Please Confirm What We Understood',
      'confirm_yes': "Yes, That's Right (हाँ, सही है)",
      'confirm_no': 'Change This (नहीं, बदलो)',
      'queue_title': 'Your OPD Token Number',
      'patients_ahead': 'Patients Ahead of You',
      'est_wait': 'Estimated Wait Time',
      'emergency_title': 'Emergency Medical Attention Needed',
      'emergency_alert_staff': 'ALERT OPD NURSE / ATTENDANT',
      'doc_scan_title': 'Scan Your Old Prescription or Reports',
      'take_photo': 'TAKE PHOTO OF DOCUMENT',
      'vitals_title': 'Vital Signs Measurement',
      'ayush_title': 'Ayurvedic Intake (Dashavidha Pariksha)',
      'hospital_services_title': 'Hospital Services & Labs',
      'hospital_map_title': 'OPD Wayfinding & Map',
      'completion_title': 'Intake Successfully Completed!',
      'reset_button': 'FINISH & RESET SCREEN',
    },
    'hi': {
      'welcome_title': 'मेडीकिओस्क में आपका स्वागत है',
      'welcome_subtitle': 'तेज़, बोलकर लक्षण दर्ज करने की ओपीडी सुविधा',
      'start_button': 'शुरू करें (START INTAKE)',
      'select_language': 'अपनी भाषा चुनें',
      'consent_title': 'मरीज़ सहमति एवं गोपनीयता सूचना',
      'consent_body':
          'मेडीकिओस्क आपके डॉक्टर की सहायता के लिए आपकी परेशानी और पुरानी पर्चियों को सुरक्षित रूप से दर्ज करता है। आपका डेटा पूरी तरह सुरक्षित है।',
      'agree_continue': 'मैं सहमत हूँ (I AGREE)',
      'identify_title': 'मरीज़ पहचान',
      'scan_abha': 'आभा (ABHA) क्यूआर कोड स्कैन करें',
      'enter_mobile': 'या अपना 10-अंकों का मोबाइल नंबर दर्ज करें',
      'skip_identify': 'पहचान छोड़ें (बिना पहचान आगे बढ़ें)',
      'care_stream_title': 'परामर्श विभाग का चयन करें',
      'voice_intake_title': 'बोलकर अपनी परेशानी बताएं',
      'tap_to_speak': 'बोलने के लिए माइक दबाएं',
      'listening': 'हम सुन रहे हैं... बोलिए',
      'processing': 'जानकारी समझ रहे हैं...',
      'summary_title': 'कृपया जाँचे जो हमने समझा',
      'confirm_yes': 'हाँ, बिल्कुल सही है',
      'confirm_no': 'नहीं, इसे बदलें',
      'queue_title': 'आपका ओपीडी टोकन नंबर',
      'patients_ahead': 'आपसे पहले मरीज़',
      'est_wait': 'अनुमानित प्रतीक्षा समय',
      'emergency_title': 'आपातकालीन सहायता की आवश्यकता',
      'emergency_alert_staff': 'ओपीडी नर्स को तुरंत सूचित करें',
      'doc_scan_title': 'पुरानी पर्ची या जाँच रिपोर्ट स्कैन करें',
      'take_photo': 'दस्तावेज़ की फोटो लें',
      'vitals_title': 'शारीरिक माप (Vitals)',
      'ayush_title': 'आयुर्वेदिक प्रकृति व अग्नि परीक्षण',
      'hospital_services_title': 'अस्पताल सेवाएँ एवं दवाखाना',
      'hospital_map_title': 'अस्पताल का नक्शा व दिशाएँ',
      'completion_title': 'पंजीकरण सफलतापूर्वक पूरा हुआ!',
      'reset_button': 'समाप्त करें (RESET)',
    },
    'ta': {
      'welcome_title': 'மெடிகியோஸ்கிற்கு நல்வரவு',
      'welcome_subtitle': 'வேகமான, குரல் வழி மருத்துவப் பதிவு',
      'start_button': 'தொடங்குங்கள் (START)',
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'consent_title': 'நோயாளி ஒப்புதல் மற்றும் தனியுரிமை',
      'consent_body': 'உங்கள் மருத்துவருக்கு உதவ உங்கள் அறிகுறிகள் மற்றும் ஆவணங்கள் சேகரிக்கப்படுகின்றன.',
      'agree_continue': 'நான் ஒப்புக்கொள்கிறேன்',
      'identify_title': 'நோயாளி அடையாளம்',
      'scan_abha': 'ABHA QR குறியீட்டை ஸ்கேன் செய்யுங்கள்',
      'enter_mobile': 'அல்லது மொபைல் எண்ணை உள்ளிடவும்',
      'skip_identify': 'தவிர்த்து செல்லவும்',
      'care_stream_title': 'பிரிவைத் தேர்ந்தெடுக்கவும்',
      'voice_intake_title': 'உங்கள் உடல்நலப் பிரச்சனையை பேசுங்கள்',
      'tap_to_speak': 'பேச தட்டவும்',
      'listening': 'கேட்கிறது... பேசுங்கள்',
      'processing': 'செயலாக்குகிறது...',
      'summary_title': 'விவரங்களை உறுதிப்படுத்தவும்',
      'confirm_yes': 'ஆம், சரி',
      'confirm_no': 'இல்லை, மாற்றவும்',
      'queue_title': 'உங்கள் டோக்கன் எண்',
      'patients_ahead': 'முன்னுள்ள நோயாளிகள்',
      'est_wait': 'காத்திருப்பு நேரம்',
      'emergency_title': 'அவசர சிகிச்சை தேவை',
      'emergency_alert_staff': 'மருத்துவ பணியாளருக்கு தெரிவிக்கவும்',
      'doc_scan_title': 'பழைய மருந்துச்சீட்டை ஸ்கேன் செய்யவும்',
      'take_photo': 'புகைப்படம் எடுக்கவும்',
      'vitals_title': 'முக்கிய அறிகுறிகள்',
      'ayush_title': 'ஆயுஷ் மருத்துவப் பதிவு',
      'hospital_services_title': 'மருத்துவமனை சேவைகள்',
      'hospital_map_title': 'மருத்துவமனை வரைபடம்',
      'completion_title': 'பதிவு வெற்றிகரமாக முடிந்தது!',
      'reset_button': 'முடிக்கவும்',
    },
    'te': {
      'welcome_title': 'మెడికియోస్క్‌కు స్వాగతం',
      'welcome_subtitle': 'వాయిస్ ఆధారిత వేగవంతమైన ఓపీడీ నమోదు',
      'start_button': 'ప్రారంభించండి (START)',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'consent_title': 'రోగి సమ్మతి & గోప్యతా నోటీసు',
      'consent_body': 'మీ వైద్యుడికి సహాయపడటానికి మీ వివరాలు మరియు రిపోర్టులు సేకరించబడుతున్నాయి.',
      'agree_continue': 'నేను అంగీకరిస్తున్నాను',
      'identify_title': 'రోగి గుర్తింపు',
      'scan_abha': 'ABHA QR కోడ్‌ను స్కాన్ చేయండి',
      'enter_mobile': 'లేదా మొబైల్ నంబర్ నమోదు చేయండి',
      'skip_identify': 'దాటవేసి కొనసాగండి',
      'care_stream_title': 'విభాగాన్ని ఎంచుకోండి',
      'voice_intake_title': 'మీ సమస్యలను మాట్లాడి చెప్పండి',
      'tap_to_speak': 'మాట్లాడటానికి నొక్కండి',
      'listening': 'వింటున్నాము... చెప్పండి',
      'processing': 'విశ్లేషిస్తున్నాము...',
      'summary_title': 'దయచేసి వివరాలను ధృవీకరించండి',
      'confirm_yes': 'అవును, సరైనది',
      'confirm_no': 'కాదు, మార్చండి',
      'queue_title': 'మీ టోకెన్ సంఖ్య',
      'patients_ahead': 'ముందున్న రోగులు',
      'est_wait': 'వేచి ఉండే సమయం',
      'emergency_title': 'అత్యవసర చికిత్స అవసరం',
      'emergency_alert_staff': 'సిబ్బందికి సమాచారం ఇవ్వండి',
      'doc_scan_title': 'పాత ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
      'take_photo': 'ఫోటో తీయండి',
      'vitals_title': 'శరీర కొలతలు (Vitals)',
      'ayush_title': 'ఆయుష్ పరీక్ష',
      'hospital_services_title': 'ఆసుపత్రి సేవలు',
      'hospital_map_title': 'ఆసుపత్రి మ్యాప్',
      'completion_title': 'నమోదు విజయవంతంగా పూర్తయింది!',
      'reset_button': 'ముగించండి',
    },
    'mr': {
      'welcome_title': 'मेडीकिओस्क मध्ये आपले स्वागत आहे',
      'welcome_subtitle': 'जलद, बोलून लक्षणे नोंदवण्याची सुविधा',
      'start_button': 'सुरू करा (START)',
      'select_language': 'आपली भाषा निवडा',
      'consent_title': 'रुग्ण संमती व गोपनीयता माहिती',
      'consent_body': 'डॉक्टरांच्या मदतीसाठी आपली लक्षणे व कागदपत्रे सुरक्षितपणे नोंदवली जातात.',
      'agree_continue': 'मी सहमत आहे',
      'identify_title': 'रुग्ण ओळख',
      'scan_abha': 'आभा (ABHA) क्यूआर कोड स्कॅन करा',
      'enter_mobile': 'किंवा १०-अंकी मोबाईल नंबर टाका',
      'skip_identify': 'ओळख वगळा (Skip)',
      'care_stream_title': 'विभागाची निवड करा',
      'voice_intake_title': 'आपला त्रास बोलून सांगा',
      'tap_to_speak': 'बोलण्यासाठी माइक दाबा',
      'listening': 'आम्ही ऐकत आहोत...',
      'processing': 'माहिती समजून घेत आहोत...',
      'summary_title': 'कृपया आम्ही समजलेली माहिती तपासा',
      'confirm_yes': 'होय, बरोबर आहे',
      'confirm_no': 'नाही, बदला',
      'queue_title': 'आपला ओपीडी टोकन क्रमांक',
      'patients_ahead': 'तुमच्या आधीचे रुग्ण',
      'est_wait': 'अंदाजे वेळ',
      'emergency_title': 'तातडीच्या उपचारांची आवश्यकता',
      'emergency_alert_staff': 'ओपीडी नर्सला ताबडतोब कळवा',
      'doc_scan_title': 'जुने प्रिस्क्रिप्शन किंवा अहवाल स्कॅन करा',
      'take_photo': 'फोटो काढा',
      'vitals_title': 'शारीरिक तपासणी (Vitals)',
      'ayush_title': 'आयुर्वेदिक प्रकृती व अग्नी तपासणी',
      'hospital_services_title': 'रुग्णालय सेवा व औषधालय',
      'hospital_map_title': 'रुग्णालयाचा नकाशा',
      'completion_title': 'नोंदणी यशस्वीपणे पूर्ण झाली!',
      'reset_button': 'समाप्त करा (Reset)',
    },
  };
}
